require("config.keymaps.general")
require("config.keymaps.telescope")
require("config.keymaps.errors")
require("config.keymaps.oil")
require("config.keymaps.lsp")
require("config.keymaps.formatting")
require("config.keymaps.diagnostics")
-- require("config.keymaps.r")

-- require("config.keymaps.lsp")
-- require("config.keymaps.diagnostics")
-- require("config.keymaps.git")
-- require("config.keymaps.terminal")
-- require("config.keymaps.markdown")
-- require("config.keymaps.quarto")
-- require("config.keymaps.r")
-- require("config.keymaps.debug")
